[package]
name = "schiebepuzzle-solver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.75"
clearscreen = "2.0.1"
itertools = "0.11.0"
priority-queue = "1.3.2"
promptly = "0.3.1"
